name: deploy
on:
  push:
    branches:
      [ "main" ]
jobs:
  Connexion:
    runs-on: ubuntu-latest
    steps:
      - name: Connexion SSH avec le serveur
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USERNAME }}
          password: ${{ secrets.DEPLOY_PASSWORD }}
          script: |
            cd /var/www/niceform
  Copy:
    needs: Connexion
    runs-on: ubuntu-latest
    steps:
      - name: Connexion SSH avec le serveur
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USERNAME }}
          password: ${{ secrets.DEPLOY_PASSWORD }}
          script: |
            last_directory=$(basename ${{ runner.workspace }})
            cd /var/www/niceform
            
            if [ -d "niceform/.git" ]; then
              cd niceform
              git pull origin main
            else
              git clone --depth 1 --single-branch https://github.com/${{ github.repository }}.git temp_repo
              mv temp_repo/* temp_repo/.git* .
              rm -rf temp_repo/
            fi
            