name: Deploy to VPS

on:
  push:
    branches:
      - continuous-deployment

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Add SSH key to agent (securely)**
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Install dependencies (optional)
        run: |
          sudo apt-get update && sudo apt-get install -y rsync  # Install rsync

      - name: Sync files to VPS (securely)**
        run: |
          export SSH_AUTH_SOCK="$RUNNER_DIR/agent.sock"  # Use SSH agent socket

          # Avoid hardcoded paths:
          rsync -avz -e "ssh -o StrictHostKeyChecking=yes" "$GITHUB_WORKSPACE/" ${{ secrets.VPS_DEPLOY_PATH }}