name: Deploy to VPS

on:
  push:
    branches:
      - continuous-deployment

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{secrets.SSH_PRIVATE_KEY}}

      - name: Sync files to VPS
        run: |
          rsync -avz -e "ssh -o StrictHostKeyChecking=no" ./ ${{secrets.VPS_USER}}:/var/www/niceforms
        env:
          SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}