name: Niceform Deploy

on:
  push:
    branches:
      - experiment/auto-deployment

jobs:
  deploy:
    runs-on: ubuntu-23.04

    steps:
    - name: ssh deploy
      uses: easingthemes/ssh-deploy@v5.0.3
      with:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
        REMOTE_USER: ${{ secrets.REMOTE_USER }}
        SOURCE: "dist/"
        TARGET: "/var/www/niceform"
        ARGS: "-rlgoDzvc -i"
        SCRIPT_BEFORE: |
          whoami
          ls -al
        SCRIPT_AFTER: |
          whoami
          ls -al
          echo $RSYNC_STDOUT
