name: deploy
on:
  push:
    branches:
      [ "experiment/auto-deploy" ]
jobs:
  Connexion:
    runs-on: ubuntu-latest
    steps:
      - name: Connexion SSH avec le serveur
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USERNAME }}
          password: ${{ secrets.DEPLOY_PASSWORD }}
          script: |
            cd /var/www/niceform
  Copy:
    needs: Connexion
    runs-on: ubuntu-latest
    steps:
      - name: Connexion SSH avec le serveur
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USERNAME }}
          password: ${{ secrets.DEPLOY_PASSWORD }}
          script: |
            last_directory=$(basename ${{ runner.workspace }})
            cd /var/www/niceform
            git clone https://github.com/${{ github.repository }}.git 
  Restart:
    needs: Copy
    runs-on: ubuntu-latest
    steps:
      - name: Restart apache2
        run: |
          systemctl restart apache2